services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
  
  
  flask:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=Scrap.py
    ports:
      - 5000:5000